version: '3'

services:
  mongodb-book:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb-book-data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongodb-book-data:
